# serverless.yml - Serverless Framework configuration
service: news-summarizer

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  stage: dev
  
  environment:
    DYNAMODB_TABLE: news-summarizer-cache
    HUGGINGFACE_API_TOKEN: ${env:HUGGINGFACE_API_TOKEN}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  summarize:
    handler: src/lambda_function.lambda_handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /summarize
          method: post
          cors: true
      - http:
          path: /summarize
          method: options
          cors: true

resources:
  Resources:
    NewsSummarizerCacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: cache_key
            AttributeType: S
        KeySchema:
          - AttributeName: cache_key
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false